<?php

use Illuminate\Support\Facades\File;

/**
 * `clean-arch:make-observer {name} {domain}` writes `{name}Observer.php`, so
 * the class it declares has to follow `{name}` as well. It used to follow
 * `{domain}`, which agrees with the file only in the documented usage,
 * `make-observer Article Article`, and breaks PSR-4 autoloading as soon as
 * the two diverge. The model the observer imports and type hints keeps
 * following `{domain}`.
 */
describe('Observer class name', function () {

    afterEach(function () {
        foreach ([app_path('Domain'), app_path('Application'), app_path('Infrastructure')] as $dir) {
            if (File::isDirectory($dir)) {
                File::deleteDirectory($dir);
            }
        }
    });

    it('names the class after the given name', function () {
        $this->artisan('clean-arch:make-observer', ['name' => 'StoreObserver', 'domain' => 'Store'])
            ->assertExitCode(0);

        $path = app_path('Infrastructure/Observers/Stores/StoreObserver.php');
        expect(File::exists($path))->toBeTrue();
        expect(File::get($path))->toContain('class StoreObserver');
    });

    it('keeps the class and the file aligned when the name and the domain differ', function () {
        $this->artisan('clean-arch:make-observer', ['name' => 'StoreStock', 'domain' => 'Store'])
            ->assertExitCode(0);

        $path = app_path('Infrastructure/Observers/Stores/StoreStockObserver.php');
        expect(File::exists($path))->toBeTrue();

        $content = File::get($path);
        expect($content)->toContain('class StoreStockObserver');
        expect($content)->not->toContain('class StoreObserver');
    });

    it('still imports and type hints the model of the given domain', function () {
        $this->artisan('clean-arch:make-observer', ['name' => 'StoreStock', 'domain' => 'Store'])
            ->assertExitCode(0);

        $content = File::get(app_path('Infrastructure/Observers/Stores/StoreStockObserver.php'));
        expect($content)
            ->toContain('use App\Domain\Stores\Models\Store;')
            ->toContain('public function created(Store $store): void');
    });

    it('is unchanged when the name and the domain agree', function () {
        $this->artisan('clean-arch:make-observer', ['name' => 'Article', 'domain' => 'Article'])
            ->assertExitCode(0);

        $path = app_path('Infrastructure/Observers/Articles/ArticleObserver.php');
        expect(File::exists($path))->toBeTrue();
        expect(File::get($path))->toContain('class ArticleObserver');
    });

    it('leaves no placeholder behind in an observer generated by make-domain', function () {
        $this->artisan('clean-arch:make-domain', ['name' => 'Article'])
            ->expectsConfirmation('Would you like to generate an Observer?', 'yes')
            ->expectsConfirmation('Would you like to generate a Listener?', 'no')
            ->expectsConfirmation('Would you like to generate a Job?', 'no')
            ->expectsConfirmation('Would you like to generate a Mail?', 'no')
            ->expectsConfirmation('Would you like to generate a Notification?', 'no')
            ->expectsConfirmation('Would you like to generate an Export?', 'no')
            ->assertExitCode(0);

        $content = File::get(app_path('Infrastructure/Observers/Articles/ArticleObserver.php'));
        expect($content)
            ->toContain('class ArticleObserver')
            ->not->toContain('{{ObserverName}}');
    });
});
